services:
    ubuntu:
        public: true
        container_name: tzchz
        image: accetto/ubuntu-vnc-xfce:latest
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=vnc
            - GEOMETRY=1280x720
            - TZ=America/Costa_Rica
            - DEPTH=24
        volumes: 
            - /home
        resources:
          cpu: 1000m
          memory: 3072Mi
          storage:
            size: 1Gi
            class: standard
